name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dnfile
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install tox
      run: pip install tox
    - name: Lint with isort and pycodestyle
      run: tox -e lint
    - name: Check types with mypy
      run: tox -e type

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dnfile
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install tox
      run: pip install tox
    - name: Run tests
      run: tox -e py38
